### PR TITLE
Member self sign up

### LINKED ISSUE #357: Members can register themselves
Easy to use register page for members when they come to check in and they are not registered.
Should be broken up into pages for each category, so we don't overload them with information.
- [ ] If no results are found, show option to register in search results

### PR DESCRIPTION
**Pull request by sambehrens**
closes #357

### CODE REVIEW

File: client/src/components/pages/members/memberCheckIn/pages/SelfRegisterMember.js [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+                <div className="panel">
+                    <h1 className="panel-title">Sign up</h1>
+                    <DynamicForm
+                        inputs={memberInputs}
+                        onChange={this.handleChange}
+                        onSubmit={this.onSubmit}
+                        submitButtonLabel="Sign up"
+                        errors={this.props.errors}
+                        values={this.state}
+                        errorDescription="There are snakes in this boot."
```
Comment (karlmolina) [inline client/src/components/pages/members/memberCheckIn/pages/SelfRegisterMember.js]: wth

**Review by karlmolina — CHANGES_REQUESTED** [review]

File: client/src/components/pages/members/memberCheckIn/pages/SelfRegisterMember.js [hunk 2]
```diff
@@ -0,0 +1,75 @@
+import { bindActionCreators } from 'redux';
```
Comment (karlmolina) [inline client/src/components/pages/members/memberCheckIn/pages/SelfRegisterMember.js:1]: shouldn't there be like a RegisterMemberPage and a RegisterMember component, because this is just like the register member page.

**Review by karlmolina — APPROVED** [review]
